# Generated by Django 4.0.3 on 2022-04-08 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beer_tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_text', models.CharField(max_length=255)),
                ('beer_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Beer_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Beer_tags',
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_types',
            field=models.ManyToManyField(to='beer_tags.beer_type'),
        ),
        migrations.AddField(
            model_name='beer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
